---
- name: Creates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0775'
    force: false
  with_items:
    - "{{ app_home_dir }}"
    - "{{ jira_home }}"
    - "{{ jira_data }}"
    - "{{ jira_data }}/lib"
    - "{{ jira_data_db }}"

- name: Copy Drivers
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0644'
  with_items:
    - { src: "mysql-connector-j-8.1.0.jar", dest: "{{ jira_data }}/lib" }

- name: Copy file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0644'
    backup: true
  with_items:
    - { src: '.env.j2', dest: '{{ jira_home }}/.env' }
    - { src: 'docker-compose.yml.j2', dest: '{{ jira_home }}/docker-compose.yml' }

- name: Restart jira
  ansible.builtin.shell: echo success
  notify:
    Restart jira
